@startuml creationPilote
participant index.jsp as accueil
participant CreationPiloteServlet as serlvet
participant creationPilote.jsp as creation
database ModeleJPA as bdd

accueil -> serlvet: http GET
serlvet -> creation : http GET
activate serlvet
activate creation
creation -> creation : formulaire
creation -> serlvet : http POST
deactivate creation
serlvet -> bdd : createEntityManagerFactory
activate bdd
bdd --> serlvet :
serlvet -> serlvet : creation du Pilote
serlvet -> bdd : persistance du Pilote
bdd --> serlvet
deactivate bdd
serlvet -> creation : http POST
deactivate serlvet
@enduml