@startuml creationPilote
participant index.jsp as accueil
participant CreationPiloteServlet as serlvet
participant creationPilote.jsp as creation
database ModeleJPA as bdd

accueil -> serlvet: http GET
serlvet -> creation : http GET
creation -> creation : formulaire
creation -> serlvet : http POST
serlvet -> bdd : createEntityManagerFactory
bdd --> serlvet :
serlvet -> serlvet : creation du Pilote
serlvet -> bdd : persistance du Pilote
bdd --> serlvet: 
serlvet -> creation : http POST
@enduml