@startuml Liste Pilotes
entity index.jsp
entity rechercheAvanceePiloteServlet as RAPS
entity rechercheAvanceePilote.jsp as rap
entity listePilotes.jsp
entity ListePilotesServlet as LPS
entity ModèleJPA
database BDD

  index.jsp -> LPS: http GET
  activate LPS
  LPS -> ModèleJPA: JPQL
  activate ModèleJPA
  ModèleJPA -> BDD: jdbc
  activate BDD
  BDD --> ModèleJPA
  deactivate BDD
  ModèleJPA --> LPS
  deactivate ModèleJPA

LPS -> listePilotes.jsp: forward(http GET) Liste<Pilote>
deactivate LPS
@enduml