@startuml RechercheAvanceePilote
entity index.jsp
entity rechercheAvanceePiloteServlet as RAPS
entity rechercheAvanceePilote.jsp as rap
entity listePilotes.jsp
entity ListePilotesServlet as LPS
entity ModèleJPA
database BDD

  index.jsp -> RAPS: http GET
  activate RAPS
  RAPS -> rap: http GET
  activate rap
  rap -> rap: formulaire
  rap -> RAPS: http GET
  deactivate rap
  RAPS -> RAPS: génère la requête
  RAPS -> ModèleJPA: JPQL
  deactivate RAPS
  activate ModèleJPA
  ModèleJPA -> BDD: jdbc
  activate BDD
  BDD --> ModèleJPA
  deactivate BDD
  ModèleJPA --> LPS
  deactivate ModèleJPA
  activate LPS
  LPS -> LPS : recherche sur les grades
  LPS -> listePilotes.jsp: forward(http GET) Liste<Pilote>
  deactivate LPS
@enduml