@startuml Cloture Mission
entity listeMissions.jsp
entity detailMission.jsp
entity DetailMissionServlet as DMS
entity ClotureMissionServlet as CMS
database ModèleJPA

listeMissions.jsp -> DMS: http GET
activate DMS
DMS -> ModèleJPA: find()
activate ModèleJPA
ModèleJPA --> DMS: Mission
deactivate ModèleJPA
DMS -> detailMission.jsp: forward (http GET)
deactivate DMS
activate detailMission.jsp
detailMission.jsp -> CMS: http POST
deactivate detailMission.jsp
activate CMS
CMS -> ModèleJPA: find()
activate ModèleJPA
ModèleJPA --> CMS: Mission
CMS -> CMS: Mise à jour
CMS -> ModèleJPA: commit
CMS -> listeMissions.jsp: forward (http POST)
@enduml