@startuml Diag_classe_projet_Java

class Chasseur {
    id
    listeChasseur : Arraylist
    chasseur : TypeChasseur
    etat : EtatChasseur
    pilote : Pilote
}

enum TypeChasseur {
    X-wing
    Y-wing
}

enum EtatChasseur {
    Operationnel
    Maintenance
    Detruit
}

class Personne {
    prenom : String
    nom : String
    id
}

class Recuteur {

}

class Pilote {
    listePilote : Arraylist
    race : RacePilote
    age : int
    etat : EtatPilote
    grade : GradePilote
    heureVol : int
    chasseur : Chasseur
    formationValidee : boolean
    enMission : boolean
}

enum RacePilote {
    toutes les races
}

enum EtatPilote {
    Disponible
    Blesse
    En mission
    Tue
}

enum GradePilote {
    Officier de Vol
    Lieutenant
    Capitaine
    Commandant
}

Chasseur --> TypeChasseur
Chasseur --> EtatChasseur

Pilote --|> Personne
Recuteur --|> Personne

Pilote --> RacePilote
Pilote --> EtatPilote
Pilote --> GradePilote

Chasseur .. Pilote

@enduml